### ISSUE TITLE
Delete Server Using - DELETING BUTTON

### ISSUE THREAD

**Issue by Amagida** [Bios-Marcel/ServerBrowser#14]
So at this moment, when i want to remove server from favourites, i have to select server then click mouse right button and then click remove server from favourites. This will be really good if we can do this with only select server and delete button.

**Comment by Bios-Marcel** [comment]
Implemented with https://github.com/Bios-Marcel/ServerBrowser/commit/032e935049f578d7354bf3a2302f3e88cd9d45ac
