### ISSUE TITLE
Suggestion: Server history

### ISSUE THREAD

**Issue by r1karim** [Bios-Marcel/ServerBrowser#30]
a list of servers that we joined.

**Comment by billz1471** [comment]
There's no point really mate. All the servers we go on we just favourite it. If you would like to see your recent server you have played and don't know the IP, then just check the chat log, then add it to your favourites.

**Comment by Bios-Marcel** [comment]
@billz1471 I disagree, what if you joined 50 servers in a row? Will you add them all to your favourites, that'd mean spamming your favourites like hell. Also, searching through the chat log is annoying.

**Comment by billz1471** [comment]
@Bios-Marcel Hello sir. I am a big fan of your launcher and I have replaced this with the current SA-MP launcher made by Kalcor who owns SA-MP. I partially agree with this. I only agree with the bit searching through chat log is annoying.

However, it's not like you're going to play 50 different servers at one day. This number will build up across the weeks you play. I reckon you play a NEW server every few weeks or so, maybe months depending on people. As soon as you play a server, just favourite it etc. It's not like you're going to play 10 different servers in one day and you need to scroll up the chatlog to find it all.

Thank you.

**Comment by Bios-Marcel** [comment]
A server history would date far back though. That'd be a huge pluspoint, also, i really don't want to abuse the `Add to favourites` feature, it's supposed to be things you actually like and not things you join once. I always go the way that allows me to be as careless as possible, that'd be a server history.

**Comment by billz1471** [comment]
I mean I am not totally against the idea but this shouldn't be on your top priority list. But instead, this should be something done when everything is perfected. This is just a simple little feature that won't effect anything major.

I actually don't mind to be honest.

**Comment by Bios-Marcel** [comment]
There is no such thing as perfection in `software`. Every software is in an everlasting state of improvement and expansion (well not every maybe :D) . I am unsatisfied with a lot of things. And ofc adding new features is kind of important to get more people to use it. If there are no interesting features, why'd anyone use it ;)

**Comment by Bios-Marcel** [comment]
What do u think about this:

https://i.imgur.com/csd2WgC.png

**Comment by Bios-Marcel** [comment]
Feature has been implemented in a basic way.
