### ISSUE TITLE
Making this into a true cross-platform app

### ISSUE THREAD

**Issue by Bios-Marcel** [Bios-Marcel/ServerBrowser#33]
SA-MP is a windows only thing, but GTA SA is mostlikely playable via Wine on Unix systems. So it'd be interesting if it'd be possible to actually build a bridge between wine and this software, so a Unix user could make use of this software. Maybe even MacOS would be possible? No clue, but i can't test that anyways.

**Comment by billz1471** [comment]
I totally agree with this, I would love this to happen!

**Comment by Bios-Marcel** [comment]
Introduced with c83c4026e57faa70584f0253535a5353bdefefae and d06a367d155e367084b4340189ebfa2bdab76fe1 .

For now only Username reading and writing and connecting to servers is supported. Reading chatlogs and stuff has to be done later.
