### ISSUE TITLE
App can't find GTA installation

### ISSUE THREAD

**Issue by Catalin-Mihai** [Bios-Marcel/ServerBrowser#40]
I am using the latest released version 8.5.2
The app can't find the game installation path so i wrote it manually. Seems that it's not enough. 
I'm doing something wrong?

Also, it's normal to let the app install only on the AppData\Local folder? Can you add a custom installation destination?

https://imgur.com/a/Gn9Im

**Comment by Bios-Marcel** [comment]
It might be helpful if you send me your log files, they are located at `%userprofile%/sampex/Log.log`.

Also, about the path of  installation, by using AppData i assure that user doesn't have to be admin.

I could allow custom paths though i guess.

**Comment by Bios-Marcel** [comment]
Oh and btw, the picture is super low quality, can't read anything.

**Comment by Catalin-Mihai** [comment]
https://pastebin.com/z9L1wTsx

**Comment by Catalin-Mihai** [comment]
![untitled](https://user-images.githubusercontent.com/12239126/35328084-eb2271e2-0103-11e8-826b-7d620b4351a9.png)

**Comment by Bios-Marcel** [comment]
Mind appending a `\`?

**Comment by Catalin-Mihai** [comment]
No effect

**Comment by Bios-Marcel** [comment]
Can't help you any further in that case, since i am currently not at home.

**Comment by Bios-Marcel** [comment]
What did you try doing? Switch SA-MP version or connect to a server?

**Comment by Bios-Marcel** [comment]
Ah i might have one more idea. Instead of the Gta path, enter the samp path!

The label actually says so ^^

**Comment by Catalin-Mihai** [comment]
I wanted to install sa-mp 0.3.7 R2 from sa-mp.com but i remembered about your server browser.
Do i need sa-mp installed before using this app?

**Comment by Bios-Marcel** [comment]
Maybe, i don't have aldetails in my head. l

**Comment by Catalin-Mihai** [comment]
Yeh, that was the problem. Now it works right.
Anyway, it would be nice to have only your app installed without a previous sa-mp install.

**Comment by Bios-Marcel** [comment]
True, mind creating a new issue for that?

**Comment by Catalin-Mihai** [comment]
I'll do that

**Comment by Bios-Marcel** [comment]
Thanks
