### ISSUE TITLE
ServerBrowser can't install a new sa-mp version without an already installed one

### ISSUE THREAD

**Issue by Catalin-Mihai** [Bios-Marcel/ServerBrowser#41]
You must have sa-mp already installed in order to get SeverBrowser's switch version feature working.
It should install a new sa-mp version without the need of an old one.

**Comment by Bios-Marcel** [comment]
Resolved: 

* https://github.com/Bios-Marcel/ServerBrowser/commit/caf3d76f528dfdf40c8a1b76dd7253018df3d6e0
* https://github.com/Bios-Marcel/ServerBrowser/commit/ed3dde8ddff2a3824b00868b2c26bdb44ca38acf

will be included in next release.
