### ISSUE TITLE
Chatlog moving part of the scrollbar is bugged

### ISSUE THREAD

**Issue by IstuntmanI** [Bios-Marcel/ServerBrowser#47]
When scrolling down the first time the scrollbar will get filled with the same color and when you are moving up the scrollbar it will remain the same, with the buggy filled color.

**Comment by Bios-Marcel** [comment]
Probably not only for the Chatlog

**Comment by IstuntmanI** [comment]
Tested it for "version changer" and "settings" (the only two places where I found a scrollbar by default) tabs and it works fine.

**Comment by Bios-Marcel** [comment]
Fixed with https://github.com/Bios-Marcel/ServerBrowser/commit/59445d41909a7387d6e0cf005c9237a0651e980c
