### ISSUE TITLE
More translation suggestion

### ISSUE THREAD

**Issue by Tagic** [Bios-Marcel/ServerBrowser#50]
I translate Lang_en.properties file to bosnian language and i can't find this list: 

![image](https://user-images.githubusercontent.com/28901520/35771313-f3acc748-092a-11e8-9aac-59254649bac6.png)

You should add them in file like:

- connectToServer=Conect to server
- removeFromFavourites=Remove from favourites
- copyIpAddresAndPort=Copy IP Addres And Port
- visitWebsite=Visit Website

**Comment by Bios-Marcel** [comment]
Indeed, i forgot those, ty
