### ISSUE TITLE
Padlock on side suggestion

### ISSUE THREAD

**Issue by Tagic** [Bios-Marcel/ServerBrowser#52]
Like in default launcher:

- Green icon for servers without password.
- Red icon for servers with password.

![image](https://user-images.githubusercontent.com/28901520/35771775-70fc794e-0932-11e8-8282-9a22c350b5f3.png)

**Comment by Bios-Marcel** [comment]
Wont work as of now, since i am using a backend which doesnt suport specifying data that i wanna retrieve

**Comment by BigETI** [comment]
This feature might be a possibility in the future.

**Comment by Bios-Marcel** [comment]
Done with 592b7ec00f81854eccdd95b8fbb45b6f67f0d1dd

Servers with a password will have a padlock, servers without a password won't have a padlock.

![Preview](http://i.imgur.com/Y4fxL4W.png)
