### ISSUE TITLE
Server password is passed incorrectly

### ISSUE THREAD

**Issue by Berndwl** [Bios-Marcel/ServerBrowser#60]
Couldn't connect to a password protected server, samp constantly gave me an invalid password message.

the buildLaunchingArguments has a typo which passes the wrong arg for the server password:

			if (!password.isEmpty()) {
				arguments.add("z");
				arguments.add(password);
			}

should be `arguments.add("-z");`

as far as I know?

**Comment by Bios-Marcel** [comment]
you are right, i am retarded ...

**Comment by Berndwl** [comment]
Happens to the best 😃
