### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by masudr4n4** [Bios-Marcel/ServerBrowser#63]
Hallo @Bios-Marcel 
Great to know your projects and interesting to make a logo for this projects as i am a graphics designer.If you have any requirements then let me know.Its free for any open source projects.
Thank you

**Comment by Bios-Marcel** [comment]
Hey,

Thanks for the offer, I myself don't have much imagination, but feel free to offer any design proposals if you have any.

**Comment by masudr4n4** [comment]
![server browser-01](https://user-images.githubusercontent.com/34313493/42133063-41560a02-7d45-11e8-9712-f7e94d80f312.jpg)

**Comment by Bios-Marcel** [comment]
I don't really think that fits the application. Looks quite business-like, if you get what i mean. Afterall it's a launcher for a game from 2004 ^^'.
